plugins:
  - jekyll-relative-links
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

title: Kyoto Lesson
description: We Can All Learn to Code!
github.repository_url: ksdavidc.github.io/kyoto-lesson.github.io/
theme: jekyll-theme-leap-day

markdown: kramdown
kramdown:
    parse_block_html: true
